### ISSUE TITLE
Build failure issue on local server

### ISSUE THREAD

**Issue by dpshepherd** [PreibischLab/BigStitcher-Spark#3]
Hi all,

I just pulled the most release recent (about 10 minutes ago) and tried to build this project on our Linux Mint 19 server.

Running (added flags to get debugging):
`mvn -e -X clean package -P fatjar`

I get a build error. I have attached the build log at the end of this message.

It looks like it might be a Java version mismatch? Any suggestions on how to correctly build the project? I can change the Java JDK if I know which one to install. 

Relevant versions:

```linux
mvn -version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.13, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-74-generic", arch: "amd64", family: "unix"
```

[log.txt](https://github.com/PreibischLab/BigStitcher-Spark/files/7791412/log.txt)

Thanks!

**Comment by dpshepherd** [comment]
I removed the existing open-jdk install and installed java-1.8 jdk instead. This worked and created a clean build for the plugin. I'll hopefully get it running on our local Spark in the next day or two.

**Comment by StephanPreibisch** [comment]
Great, good luck! It should also run on newer JDKs by the way! The fix that @trautmane (see the other issue) did is not yet there by default … will release very soon!

**Comment by dpshepherd** [comment]
I pulled the n5 fix branch when I built it. Any suggestions on how to build using a newer version of openJDK? I don't know much about the Java build system, but can try to figure out if you give some pointers.
